import './style.css'
// import './02_string_number_dom/string.ts'
// import './02_string_number_dom/number.ts'
import './02_string_number_dom/string_aufgaben.ts'
import './02_string_number_dom/number_aufgaben.ts'
import './03 conditionals/conditionals_aufgaben.ts'
import './04 math/math_aufgaben.ts'
import './05 Date/date_aufgaben.ts'
import './06_Functions/Funktionen_Aufgaben.ts'
import './07_Project-TS Spielstandsanzeige/spielstand.css'
import './08_Arrays/arrays_aufgaben.ts'
import './08_Arrays/array_bonus.ts'
import './08_Arrays/array_sort_aufgaben.ts'
import './08_Arrays/arrays_III.ts'

