import './style.css'
// import './02_string_number_dom/string.ts'
// import './02_string_number_dom/number.ts'
// import './02_string_number_dom/string_aufgaben.ts'
// import './02_string_number_dom/number_aufgaben.ts'
// import './03 conditionals/conditionals_aufgaben.ts'
// import './04 math/math_aufgaben.ts'
// import './05 Date/date_aufgaben.ts'
// import './06_Functions/Funktionen_Aufgaben.ts'
// import './07_Project-TS Spielstandsanzeige/spielstand.css'
// import './08_Arrays/arrays_aufgaben.ts'
// import './08_Arrays/array_bonus.ts'
// import './08_Arrays/array_sort_aufgaben.ts'
// import './08_Arrays/arrays_III.ts'
// import './09_Loops/loops_aufgaben.ts'
// import './09_Loops/loops_aufgaben_II.ts'
// import './10_Math_&_Objects/math.ts'
// import './10_Math_&_Objects/objects.ts'
// import './10_Math_&_Objects/objects_II'
// import './11_Project-TS Trinkgeldrechner/trinkgeld'
// import './12_DOM/dom_aufgaben'
// import './12_DOM/dom_aufgaben'
// import './13_Functions_II/functions_II'
// import './14_Module_Namensraeume/app'
// import './15_Clean_Code/clean_code'
import './16_OOP/app.ts'

